# Configuración de herramientas Volta
VOLTA_PACKAGES=(
  "node"
  "npm"
  "@nestjs/cli"
)

# Paquetes npm globales (solo si no hay Volta)
NPM_GLOBALS=(
  "@nestjs/cli"
)

UV_TOOLS=(
  "sqlit-tui"
  "markitdown[all]"
)

